project_id = "xqquqrsqtnjnzvyubhzc"

[functions.parse-channels]
verify_jwt = false

[functions.aggregate-analytics]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.external-api-sync]
verify_jwt = false

[functions.external-api-webhook]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false
