project_id = "xqquqrsqtnjnzvyubhzc"

[functions.parse-channels]
verify_jwt = true

[functions.aggregate-analytics]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false
